# Generated by Django 2.1.5 on 2019-02-21 18:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50)),
                ('phoneNum', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('delAddress', models.CharField(max_length=50)),
                ('delLong', models.DecimalField(decimal_places=6, max_digits=9)),
                ('delLat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('purAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('numDeliveries', models.IntegerField(max_length=50)),
                ('totPurAmnt', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('storeLocation', models.CharField(max_length=50)),
                ('storeLong', models.DecimalField(decimal_places=6, max_digits=9)),
                ('storeLat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('numDeliveries', models.IntegerField(max_length=50)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='demandTracker.State')),
            ],
        ),
        migrations.AddField(
            model_name='sites',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='demandTracker.State'),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='demandTracker.Stores'),
        ),
        migrations.AddField(
            model_name='customers',
            name='deliveries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='demandTracker.Deliveries'),
        ),
    ]
