<<<<<<< HEAD
# Generated by Django 2.1.5 on 2019-02-21 18:18

import datetime
=======
# Generated by Django 2.1.5 on 2019-02-22 02:13

>>>>>>> d6e27679c2c0d9a838f6c18ed7a1fbb17e498418
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Customers',
=======
            name='Customer',
>>>>>>> d6e27679c2c0d9a838f6c18ed7a1fbb17e498418
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50)),
<<<<<<< HEAD
=======
                ('custLong', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('custLat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
>>>>>>> d6e27679c2c0d9a838f6c18ed7a1fbb17e498418
                ('phoneNum', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Deliveries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('delAddress', models.CharField(max_length=50)),
                ('delLong', models.DecimalField(decimal_places=6, max_digits=9)),
                ('delLat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('purAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('numDeliveries', models.IntegerField(max_length=50)),
=======
            name='Delivery',
            fields=[
                ('date', models.DateField(auto_now_add=True)),
                ('delAddress', models.CharField(max_length=50)),
                ('delLong', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delLat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('purAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'deliveries',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('numDeliveries', models.IntegerField()),
>>>>>>> d6e27679c2c0d9a838f6c18ed7a1fbb17e498418
                ('totPurAmnt', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
>>>>>>> d6e27679c2c0d9a838f6c18ed7a1fbb17e498418
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('storeLocation', models.CharField(max_length=50)),
                ('storeLong', models.DecimalField(decimal_places=6, max_digits=9)),
                ('storeLat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('numDeliveries', models.IntegerField(max_length=50)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='demandTracker.State')),
            ],
        ),
        migrations.AddField(
            model_name='sites',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='demandTracker.State'),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='demandTracker.Stores'),
        ),
        migrations.AddField(
            model_name='customers',
            name='deliveries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='demandTracker.Deliveries'),
=======
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=50)),
                ('storeLong', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('storeLat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('numDeliveries', models.IntegerField()),
                ('stateId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='demandTracker.State')),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='stateId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='demandTracker.State'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='storeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='demandTracker.Store'),
        ),
        migrations.AddField(
            model_name='customer',
            name='deliveryId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='demandTracker.Delivery'),
>>>>>>> d6e27679c2c0d9a838f6c18ed7a1fbb17e498418
        ),
    ]
