# Generated by Django 2.1.5 on 2019-02-22 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50)),
                ('custLong', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('custLat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phoneNum', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('date', models.DateField(auto_now_add=True)),
                ('delAddress', models.CharField(max_length=50)),
                ('delLong', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delLat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('purAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'deliveries',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('numDeliveries', models.IntegerField()),
                ('totPurAmnt', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=50)),
                ('storeLong', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('storeLat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('numDeliveries', models.IntegerField()),
                ('stateId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='demandTracker.State')),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='stateId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='demandTracker.State'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='storeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='demandTracker.Store'),
        ),
        migrations.AddField(
            model_name='customer',
            name='deliveryId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='demandTracker.Delivery'),
        ),
    ]
