# Generated by Django 2.1.5 on 2019-02-21 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandTracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='numDeliveries',
        ),
        migrations.RemoveField(
            model_name='stores',
            name='numDeliveries',
        ),
    ]
