# Generated by Django 2.1.5 on 2019-02-21 20:30

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('demandTracker', '0002_auto_20190221_2018'),
    ]

    operations = [
        migrations.RenameModel(
            'Customers', 'Customer',
        ),
        migrations.RenameModel(
            'Deliveries', 'Delivery',
        ),
        migrations.RenameModel(
            'Sites', 'Site',
        ),
        migrations.RenameModel(
            'Stores', 'Store',
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name_plural': 'deliveries'},
        ),
    ]
